import type { Step } from "../domain/contracts";
import type { Locale } from "../domain/locale";

export const LOCALE_STORAGE_KEY = "understanding-lab:ui-locale";

export function resolveLocale(saved: string | null, languages: readonly string[]): Locale {
  if (saved === "en" || saved === "zh-CN") return saved;
  for (const language of languages) {
    if (/^en(?:-|$)/i.test(language)) return "en";
    if (/^zh(?:-|$)/i.test(language)) return "zh-CN";
  }
  return "en";
}

export function readLocalePreference(): Locale {
  let saved: string | null = null;
  try { saved = localStorage.getItem(LOCALE_STORAGE_KEY); } catch { /* Browsers can block storage. */ }
  const languages = typeof navigator === "undefined" ? [] : navigator.languages ?? [navigator.language];
  return resolveLocale(saved, languages);
}

export function saveLocalePreference(locale: Locale): void {
  try { localStorage.setItem(LOCALE_STORAGE_KEY, locale); } catch { /* In-memory selection still works. */ }
}

const zh = {
  colon: "：", comma: "，", semicolon: "；", fullStop: "。",
  pendingLanguage: (language: string) => `这次请求仍使用 ${language}，不会因切换语言重新发送。`,
  originalLanguage: (response: string, evidence: string) => `反馈原语言：${response}；依据材料：${evidence}`,
  appName: "理解实验室", eyebrow: "理解实验室 · 过拟合", tagline: "阅读证据、写下解释，再用真实数值观察变化。离线引导，不是 AI 评价。",
  skipLink: "跳到主要内容", login: "登录", logout: "退出登录", currentAccount: (id: string) => `当前账号 ${id}`,
  local: "仅本机", syncing: "正在保存到账号", synced: "已同步到账号", conflict: "与账号中的版本冲突", offline: "账号暂时不可用", deleted: "账号中的记录已删除",
  corruptTitle: "本机草稿损坏", corruptBody: "原始内容仍保留在浏览器中。可以先导出，再决定是否丢弃并开始新尝试。", exportCorrupt: "导出损坏草稿", discardCorrupt: "丢弃损坏草稿并开始",
  conflictTitle: "与账号中的版本冲突", conflictBody: "本机完整草稿仍保留，没有自动覆盖。账号反馈若来自本机恢复，不能当作模型调用证明。可先导出本机副本，再决定载入账号版本，或另存为新尝试。", exportLocal: "导出本机副本", loadCloud: "载入账号版本", saveNew: "另存为新尝试",
  signOutTitle: "还有未同步的账号内容", signOutBody: "退出会清除这个账号在这台设备上的私人缓存和待同步队列，匿名试玩草稿会保留。远程删除也不会立刻擦掉离线副本。请先导出，未经确认不会丢弃仍在内存里的匿名草稿。", exportUnsynced: "导出未同步内容", signOutAnyway: "仍要退出", cancel: "取消",
  deletedTitle: "账号记录已删除", deletedBody: "本机草稿仍在。远程删除不会立刻擦掉这台设备上的离线副本。不能用旧编号复活已删除的记录。可以清除本机副本，或另存为新尝试后再保存。", clearLocal: "清除本机副本",
  introTitle: "开始一次本机学习", introBody: "回答和笔记保存在这台设备的浏览器中。你可以随时导出；不会自动上传到账号。", start: "开始学习",
  progress: "学习进度", workspace: "工作区视图", materialTab: "材料", experimentTab: "实验", explanationTab: "讲解",
  steps: { explain: "初始解释", clarify: "澄清", predict: "预测", experiment: "实验", reexplain: "再次解释", transfer: "迁移问题", summary: "小结" } as Record<Step, string>,
  quoteDetail: "引用的回答版本", answerRevision: (n: number) => `第 ${n} 版回答`, confirmedHistory: "已确认的历史文字", closeQuote: "关闭引用", clarifyRound: (n: number) => `澄清 ${n} / 2`, experimentObservation: "实验观察", myExplanation: "我的讲解", explanationLabel: "我的解释", answerPlaceholder: "用自己的话写下来；未确认的文字只保存在本机草稿中。", answerCount: (n: number) => `${n} / 4000 字；只有按“确认这段解释”后才成为正式回答。`, confirm: "确认这段解释", confirmed: (n: number) => `已确认第 ${n} 版。可以继续编辑并再次确认。`, experimentInstruction: "调整参数观察训练与验证误差，可冻结选择后揭示测试结果。记录至少一次观察再继续。", back: "返回上一步", skip: "跳过，标记未验证", startExperiment: "先做实验", continue: "继续下一步",
  notesTitle: "私人笔记", notesLabel: "我的笔记（最多 8000 字）", notesHint: "笔记不是确认回答。保存到账号时，笔记会随这次尝试一起上传；默认不会发给模型。", staleFeedback: (n: number) => `过期的历史反馈（${n}）`, staleFeedbackHint: "这些反馈对应旧的回答或实验版本，不用于当前小结。", saveError: (reason: string) => `未保存到本机：${reason}。当前尝试仍在此页面内存中。`, exportAttempt: "导出当前尝试", saveStatus: "本机草稿自动保存；确认前的文字不会作为回答发送。", saveAccount: "保存到账号", saveAccountHint: "登录不会自动上传匿名草稿。只有选择保存到账号后，确认过的学习记录才会上传；未确认的文字仍只在本机。保存到账号不会调用模型。", autoSave: "之后自动保存这次尝试。只作用于当前这次，不会把其他本机草稿上传。", sendAI: "发送给 AI", sendAIHint: "发送给 AI 需要单独同意，不会自动长期保存到账号。私人笔记默认不发送。额度按 UTC 日期计算，每天最多 30 次教学、10 次转写。发出请求不等于已经成功。", includeNotes: "把私人笔记一并发送给模型", tutorBusy: "正在请求教学反馈…",
  storageFull: "存储空间已满", storageUnavailable: "本机存储不可用", unknownError: "未知错误", emptyAnswer: "请先写下解释，或选择跳过。", confirmFailed: "确认失败", continueFailed: "无法继续", snapshotStep: "进入实验步骤后才能记录观察。", snapshotFailed: "记录失败", noLoginSession: "当前没有登录会话，本机草稿未上传。", wrongAccount: "当前登录账号与这份云端绑定不一致。", logoutFailed: "退出登录未完成，本机账号缓存已清除。匿名草稿仍保留。", loginUnavailable: "登录暂时不可用。本机草稿未上传。", tutorLogin: "发送给 AI 需要先登录。本机草稿未上传，也没有调用模型。", disagreeFailed: "无法记录异议",
  materialTitle: "主题材料", materialPending: "内容初稿，待人工核对", materialReviewed: "内容已审阅", evidence: (id: string) => `证据 ${id}`, source: "来源：", designSource: "课程设计说明",
  dataScenario: "数据情境", scenarioOption: (n: number, seed: number) => `情境 ${n}（种子 ${seed}）`, sampleSize: "样本量", noiseStd: "噪声标准差", noneNoise: "无（0）", lowNoise: "低（0.1）", highNoise: "高（0.3）", polynomialDegree: "多项式阶数", chartDescription: (n: number, low: string, high: string) => `数值图：训练样本 ${n} 个，验证样本 200 个，曲线纵轴 ${low} 至 ${high}`, fitCurve: "拟合曲线", trainPoints: "训练点 ●", validationPoints: "验证点 ○", chartRange: (low: string, high: string) => `纵轴实际范围：${low} 至 ${high}；横轴 0 至 1。`, scaleWarning: "尺度提示：这条曲线有极端值，纵轴已扩大以完整显示，点可能显得集中。", mseCaption: "当前选择的均方误差（MSE）", data: "数据", train: "训练", validation: "验证", test: "测试", experimentTitle: "预先计算的交互实验", experimentIntro: "三组固定种子的合成样本。调整参数会读取已计算的数值；这里没有实时训练，也不会发送给 AI。", packError: (reason: string) => `实验数据读取失败：${reason}`, packLoading: "正在读取实验数据…", freeze: "冻结当前选择", reveal: "揭示最终测试结果", record: "记录实验观察", frozen: (seed: number, n: number, noise: number, degree: number) => `已冻结：情境 ${seed}，样本 ${n}，噪声 ${noise}，阶数 ${degree}。`, testResult: (mse: string) => `测试 MSE：${mse}。这是冻结选择后的最终测试结果。`, testHidden: "测试结果尚未揭示。改变参数后需要重新冻结才能揭示新选择。", contaminated: "测试信息已影响后续选择；新的测试数值不再是独立证据。",
  summaryTitle: "本次小结", summaryIntro: "这里只整理你确认过的文字、跳过的环节和实验数值；没有 AI 评价，也不推断是否已掌握。", unverified: "未验证", recorded: "已记录", snapshot: (seed: number, n: number, noise: number, degree: number) => `情境 ${seed}，样本 ${n}，噪声 ${noise}，阶数 ${degree}：`, trainMse: "训练 MSE", validationMse: "验证 MSE", testMse: "测试 MSE", testNotRevealed: "测试未揭示", packUnreadable: "实验数据暂不可读", laterContaminated: "后续选择已受测试信息影响", summaryFooter: "离线引导，不是 AI 评价。",
  feedbackTitle: "教学反馈", recoveredFeedback: "本机恢复的反馈 · 不能当作模型调用证明", aiFeedback: "AI 教学反馈 · 结构已校验", followup: "追问：", quotes: "引用的原话", viewQuote: (n: number) => `查看第 ${n} 版原话`, quoteRevision: (n: number) => `第 ${n} 版`, sources: "材料依据", materialSource: (id: string) => `材料 ${id}`, unavailableLink: "无可用链接", metrics: "实验数值", missingSnapshot: "实验数值暂不可用：找不到对应的实验记录。", hiddenTestMetric: "引用的测试误差尚未揭示，不显示数值。", metricPackMissing: "暂不可用：实验数据未加载。", metricRecord: (id: string) => `（记录 ${id}）`, metricUnverified: "暂不可用：无法核对这次引用。", feedbackCaution: "结构校验不保证语义正确；教学判断仍待人工评测。", disagree: "提出异议", disagreementReason: "异议原因", recordDisagreement: "记录异议", disagreementHint: "异议随本机尝试保存，不会默认用于模型训练。",
  recordingConfirm: "覆盖还未转写的录音？", recordingUnsupported: "这个浏览器不能录音。请用文字继续。", recordingError: "录音出错。请用文字继续。", micDenied: "没有麦克风权限。请用文字继续。", recordingCanceled: "已取消录音。", transcriptionLogin: "转写需要先登录。录音不会自动成为回答。", transcribing: "正在转写…", transcribed: "转写已填入草稿。请检查文字后点“确认这段解释”，不会自动评价。", recordingHint: "可选录音：点开始才请求麦克风。最多 60 秒。转写结果只进入可编辑草稿，确认前不会发送给教学模型。", recordingNotSupported: "当前环境不支持录音，请用文字作答。", startRecording: "开始录音", stopRecording: "停止录音", cancelRecording: "取消", transcribeRecording: "转写这段录音", discardRecording: "丢弃录音", recordingPreview: "试听录音", transcriptionConsent: "转写需要单独同意。这次没有发送录音。", transcriptionInvalid: "这段录音无法转写。请改用文字，或重录后再试。", transcriptionUnauthorized: "转写需要先登录。本机草稿未上传。", transcriptionTooLarge: "录音文件超过 10MiB，没有发送给转写服务。", transcriptionTooLong: "录音超过 60 秒，服务端没有裁成合法长度。", transcriptionQuota: "今日转写次数已用完。额度按 UTC 日期计算，每天最多 10 次。", transcriptionDisabled: "转写未启用。请用文字继续。", transcriptionBusy: "转写服务正忙，请稍后重试。", transcriptionUnavailable: "转写暂时不可用。请用文字继续。", transcriptionEmpty: "转写结果为空。请编辑文字后再确认。", transcriptionCanceled: "已取消转写。录音没有自动成为回答。",
  recordingNow: "正在录音…", uploadingTranscription: "正在上传并转写…", cancelTranscription: "取消转写",
  cacheReady: "公共材料与实验数据已缓存，可离线使用", cacheUnknown: "公共离线缓存尚未确认", updateReady: "有更新，刷新使用", pageError: "页面出错", pageErrorBody: "本机草稿仍在浏览器存储里。可以导出后再刷新。这次错误没有发送到服务器。", missingRoot: "缺少页面根节点",
};

export type Messages = typeof zh;

const en: Messages = {
  colon: ": ", comma: ", ", semicolon: "; ", fullStop: ".",
  pendingLanguage: (language) => `This request still uses ${language}; switching language will not send it again.`,
  originalLanguage: (response, evidence) => `Original feedback: ${response}; source material: ${evidence}`,
  appName: "Understanding Lab", eyebrow: "Understanding Lab · Overfitting", tagline: "Read evidence, explain it in your own words, then explore real numbers. This is offline guidance, not an AI assessment.",
  skipLink: "Skip to main content", login: "Sign in", logout: "Sign out", currentAccount: (id) => `Current account ${id}`,
  local: "On this device only", syncing: "Saving to account", synced: "Synced to account", conflict: "Conflict with account version", offline: "Account temporarily unavailable", deleted: "Account record deleted",
  corruptTitle: "Local draft is damaged", corruptBody: "The original data is still in this browser. Export it before deciding whether to discard it and start again.", exportCorrupt: "Export damaged draft", discardCorrupt: "Discard damaged draft and start",
  conflictTitle: "Conflict with account version", conflictBody: "Your complete local draft remains here and has not been overwritten. Account feedback recovered from this device is not proof of a model call. Export the local copy before loading the account version or saving a new attempt.", exportLocal: "Export local copy", loadCloud: "Load account version", saveNew: "Save as new attempt",
  signOutTitle: "Unsynced account work remains", signOutBody: "Signing out clears this account's private cache and pending sync queue on this device. Anonymous practice remains. A remote deletion does not immediately erase an offline copy. Export first; an anonymous draft still in memory will not be discarded without confirmation.", exportUnsynced: "Export unsynced work", signOutAnyway: "Sign out anyway", cancel: "Cancel",
  deletedTitle: "Account record deleted", deletedBody: "Your local draft remains. Remote deletion does not immediately erase this device's offline copy. The old ID cannot revive the deleted record. Clear the local copy or save it as a new attempt.", clearLocal: "Clear local copy",
  introTitle: "Start learning on this device", introBody: "Answers and notes stay in this device's browser. You can export them at any time; they are not automatically uploaded to an account.", start: "Start learning",
  progress: "Learning progress", workspace: "Workspace views", materialTab: "Material", experimentTab: "Experiment", explanationTab: "Explanation",
  steps: { explain: "Initial explanation", clarify: "Clarify", predict: "Predict", experiment: "Experiment", reexplain: "Explain again", transfer: "Transfer question", summary: "Summary" },
  quoteDetail: "Quoted answer revision", answerRevision: (n) => `Answer revision ${n}`, confirmedHistory: "Confirmed historical text", closeQuote: "Close quote", clarifyRound: (n) => `Clarification ${n} / 2`, experimentObservation: "Experiment observation", myExplanation: "My explanation", explanationLabel: "Your explanation", answerPlaceholder: "Write in your own words; unconfirmed text stays only in this device's draft.", answerCount: (n) => `${n} / 4000 characters; only “Confirm this explanation” makes it a recorded answer.`, confirm: "Confirm this explanation", confirmed: (n) => `Revision ${n} confirmed. You can edit and confirm again.`, experimentInstruction: "Change parameters to observe training and validation error. Freeze a choice before revealing the final test result. Record at least one observation to continue.", back: "Previous step", skip: "Skip as unverified", startExperiment: "Try the experiment first", continue: "Continue",
  notesTitle: "Private notes", notesLabel: "My notes (up to 8000 characters)", notesHint: "Notes are not confirmed answers. Saving to your account uploads notes with this attempt; they are not sent to the model by default.", staleFeedback: (n) => `Outdated feedback (${n})`, staleFeedbackHint: "This feedback refers to older answers or experiment versions and is not used in the current summary.", saveError: (reason) => `Not saved on this device: ${reason}. This attempt is still in page memory.`, exportAttempt: "Export current attempt", saveStatus: "Local drafts save automatically; unconfirmed text is not sent as an answer.", saveAccount: "Save to account", saveAccountHint: "Signing in does not automatically upload an anonymous draft. Only choosing Save to account uploads confirmed learning records. Unconfirmed text stays on this device. Saving does not call a model.", autoSave: "Automatically save this attempt from now on. This applies only to this attempt and does not upload other local drafts.", sendAI: "Send to AI", sendAIHint: "Sending to AI requires separate consent and is not automatically stored long term in your account. Private notes are excluded by default. Quotas use UTC dates: up to 30 tutoring and 10 transcription calls per day. Sending a request does not mean it succeeded.", includeNotes: "Include private notes for the model", tutorBusy: "Requesting tutoring feedback…",
  storageFull: "Storage is full", storageUnavailable: "Local storage is unavailable", unknownError: "Unknown error", emptyAnswer: "Write an explanation first, or choose Skip.", confirmFailed: "Could not confirm", continueFailed: "Could not continue", snapshotStep: "Enter the experiment step before recording an observation.", snapshotFailed: "Could not record", noLoginSession: "No active sign-in session; the local draft was not uploaded.", wrongAccount: "The signed-in account does not match this cloud binding.", logoutFailed: "Sign-out did not finish. The local account cache was cleared; the anonymous draft remains.", loginUnavailable: "Sign-in is temporarily unavailable. The local draft was not uploaded.", tutorLogin: "Sign in before sending to AI. The local draft was not uploaded and no model was called.", disagreeFailed: "Could not record disagreement",
  materialTitle: "Learning material", materialPending: "Draft content, awaiting human review", materialReviewed: "Content reviewed", evidence: (id) => `Evidence ${id}`, source: "Source: ", designSource: "Course design notes",
  dataScenario: "Data scenario", scenarioOption: (n, seed) => `Scenario ${n} (seed ${seed})`, sampleSize: "Sample size", noiseStd: "Noise standard deviation", noneNoise: "None (0)", lowNoise: "Low (0.1)", highNoise: "High (0.3)", polynomialDegree: "Polynomial degree", chartDescription: (n, low, high) => `Numerical chart: ${n} training points, 200 validation points, vertical axis ${low} to ${high}`, fitCurve: "Fitted curve", trainPoints: "Training points ●", validationPoints: "Validation points ○", chartRange: (low, high) => `Vertical axis range: ${low} to ${high}; horizontal axis 0 to 1.`, scaleWarning: "Scale note: this curve has extreme values. The vertical axis expands to show them, so points may appear clustered.", mseCaption: "Mean squared error (MSE) for current selection", data: "Data", train: "Training", validation: "Validation", test: "Test", experimentTitle: "Precomputed interactive experiment", experimentIntro: "Three synthetic samples with fixed seeds. Changing parameters reads precomputed values; no live training runs and nothing is sent to AI.", packError: (reason) => `Could not load experiment data: ${reason}`, packLoading: "Loading experiment data…", freeze: "Freeze current selection", reveal: "Reveal final test result", record: "Record experiment observation", frozen: (seed, n, noise, degree) => `Frozen: scenario ${seed}, sample ${n}, noise ${noise}, degree ${degree}.`, testResult: (mse) => `Test MSE: ${mse}. This is the final test result for the frozen selection.`, testHidden: "The test result is still hidden. Freeze again after changing parameters to reveal a new choice.", contaminated: "Test information has influenced later choices; new test values are no longer independent evidence.",
  summaryTitle: "Attempt summary", summaryIntro: "This lists confirmed text, skipped steps, and experiment numbers. It is not an AI assessment and does not infer mastery.", unverified: "Unverified", recorded: "Recorded", snapshot: (seed, n, noise, degree) => `Scenario ${seed}, sample ${n}, noise ${noise}, degree ${degree}:`, trainMse: "Training MSE", validationMse: "Validation MSE", testMse: "Test MSE", testNotRevealed: "test not revealed", packUnreadable: "Experiment data currently unavailable", laterContaminated: "later choices were influenced by test information", summaryFooter: "Offline guidance, not an AI assessment.",
  feedbackTitle: "Tutoring feedback", recoveredFeedback: "Locally recovered feedback · not proof of a model call", aiFeedback: "AI tutoring feedback · structure checked", followup: "Follow-up: ", quotes: "Quoted original words", viewQuote: (n) => `View quoted words from revision ${n}`, quoteRevision: (n) => `revision ${n}`, sources: "Material sources", materialSource: (id) => `Material ${id}`, unavailableLink: "link unavailable", metrics: "Experiment numbers", missingSnapshot: "Experiment number unavailable: matching observation not found.", hiddenTestMetric: "The quoted test error has not been revealed, so its value is hidden.", metricPackMissing: "unavailable: experiment data has not loaded.", metricRecord: (id) => `(observation ${id})`, metricUnverified: "unavailable: this citation could not be checked.", feedbackCaution: "Structural checks do not guarantee semantic correctness; tutoring judgments still need human evaluation.", disagree: "Disagree", disagreementReason: "Reason for disagreement", recordDisagreement: "Record disagreement", disagreementHint: "Disagreement stays with this local attempt and is not used for model training by default.",
  recordingConfirm: "Replace the recording that has not been transcribed?", recordingUnsupported: "This browser cannot record audio. Continue with text.", recordingError: "Recording failed. Continue with text.", micDenied: "Microphone permission is unavailable. Continue with text.", recordingCanceled: "Recording canceled.", transcriptionLogin: "Sign in to transcribe. A recording does not automatically become an answer.", transcribing: "Transcribing…", transcribed: "Transcription was added to the draft. Check it, then select “Confirm this explanation”; it is not evaluated automatically.", recordingHint: "Optional recording: the microphone is requested only when you start. Maximum 60 seconds. Transcription enters an editable draft and is not sent to the tutor model until confirmed.", recordingNotSupported: "Recording is unavailable here; answer with text.", startRecording: "Start recording", stopRecording: "Stop recording", cancelRecording: "Cancel", transcribeRecording: "Transcribe this recording", discardRecording: "Discard recording", recordingPreview: "Play recording", transcriptionConsent: "Transcription needs separate consent. The recording was not sent.", transcriptionInvalid: "This recording cannot be transcribed. Use text or record again.", transcriptionUnauthorized: "Sign in to transcribe. The local draft was not uploaded.", transcriptionTooLarge: "The recording exceeds 10MiB and was not sent for transcription.", transcriptionTooLong: "The recording exceeds 60 seconds; the server did not shorten it to an allowed length.", transcriptionQuota: "Today's transcription quota is exhausted. Quotas use UTC dates, up to 10 per day.", transcriptionDisabled: "Transcription is disabled. Continue with text.", transcriptionBusy: "Transcription is busy; try again later.", transcriptionUnavailable: "Transcription is temporarily unavailable. Continue with text.", transcriptionEmpty: "Transcription returned no text. Edit the draft before confirming.", transcriptionCanceled: "Transcription canceled. The recording did not become an answer.",
  recordingNow: "Recording…", uploadingTranscription: "Uploading and transcribing…", cancelTranscription: "Cancel transcription",
  cacheReady: "Learning material and experiment data are cached for offline use", cacheUnknown: "Offline cache has not been confirmed", updateReady: "Update available; refresh to use it", pageError: "Page error", pageErrorBody: "Your local draft remains in browser storage. Export it before refreshing. This error was not sent to the server.", missingRoot: "Page root is missing",
};

export const messages: Record<Locale, Messages> = { "zh-CN": zh, en };
